# This is a basic workflow to help you get started with Actions

name: Gradle Build

# Controls when the workflow will run
on:
  push:
    branches: [ "main","test","sparsh-dev","tejas-dev"]
  pull_request:
    branches: [ "main" ]



jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
         java-version: '17'
         distribution: 'temurin'
         
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
         
      
